# Simulating models

## Preparation

In [1]:
from cobra.io import read_sbml_model

In [2]:
model = read_sbml_model('data/iJO1366.xml.gz')

In [4]:
model.solver = "glpk"

## Parsimonious flux balance analysis (pFBA) (5)

In [5]:
from cobra.flux_analysis import pfba

pFBA is the same as regular FBA except that our objective instead of maximizing the growth rate, is to minimize the total sum of absolute flux values. Since this on its own would lead to the trivial solution of all fluxes equal to zero (death), we also have the constraint that the original objective must be some fraction of its FBA solution.

In [6]:
fba_solution = model.optimize()
pfba_solution = pfba(model, fraction_of_optimum=0.95)

In [7]:
print(fba_solution.fluxes.BIOMASS_Ec_iJO1366_core_53p95M)
print(fba_solution.fluxes.abs().sum())

0.9823718127269633
709.9877713224889

In [8]:
print(pfba_solution.fluxes.BIOMASS_Ec_iJO1366_core_53p95M)
print(pfba_solution.fluxes.abs().sum())

0.9332532220906267
663.8480001666475

## Flux variability analysis (10 + 10)

### Preparation

In [9]:
from cobra.flux_analysis import flux_variability_analysis
import escher

In [10]:
core_model = read_sbml_model('data/e_coli_core.xml.gz')

In [12]:
core_model.solver = "glpk"

### Flux variability analysis

Calculate all possible maximum and minimum fluxes for all reactions using FVA

In [13]:
result = flux_variability_analysis(core_model)

Inspect the result.

In [14]:
result

             minimum       maximum
ACALD  -8.345524e-14  0.000000e+00
ACALDt -7.902708e-14  0.000000e+00
ACKr   -1.169900e-13  0.000000e+00
ACONTa  6.007250e+00  6.007250e+00
ACONTb  6.007250e+00  6.007250e+00
...              ...           ...
TALA    1.496984e+00  1.496984e+00
THD2    0.000000e+00  4.942351e-12
TKT1    1.496984e+00  1.496984e+00
TKT2    1.181498e+00  1.181498e+00
TPI     7.477382e+00  7.477382e+00

[95 rows x 2 columns]

Get an overview of a few key statistics of the resulting flux ranges.

In [15]:
result.describe()

            minimum       maximum
count  9.500000e+01  9.500000e+01
mean   2.627753e+00  2.357377e+01
std    1.069810e+01  1.439744e+02
min   -2.917583e+01 -2.917583e+01
25%   -2.922403e-14  0.000000e+00
50%    0.000000e+00  7.897284e-13
75%    4.959985e+00  5.012180e+00
max    4.551401e+01  1.000000e+03

Visualize the flux ranges on a pathway map of _E. coli's_ central carbon metabolism.

In [24]:
abs_flux_ranges = abs(result.maximum - result.minimum).to_dict()
escher.Builder('e_coli_core.Core metabolism', reaction_data=abs_flux_ranges).display_in_notebook()

Downloading Map from https://escher.github.io/1-0-0/6/maps/Escherichia%20coli/e_coli_core.Core%20metabolism.json

Exception: display_in_notebook is deprecated. The Builder is now a Jupyter Widget, so you can return the Builder in a cell to see it, or use the IPython display function (see Escher docs for details)

Those reactions showing up in red are futile cyles.

In [17]:
result[result.maximum > 500]

        minimum      maximum
FRD7   0.000000   994.935624
SUCDi  5.064376  1000.000000

### Loopless FVA

We add constraints to get rid of the loops using [cycle free flux](https://academic.oup.com/bioinformatics/article-lookup/doi/10.1093/bioinformatics/btv096).

In [16]:
loopless_result = flux_variability_analysis(core_model, loopless=True)

In [25]:
abs_flux_ranges = abs(loopless_result.maximum - loopless_result.minimum).to_dict()
escher.Builder('e_coli_core.Core metabolism', reaction_data=abs_flux_ranges).display_in_notebook()

Downloading Map from https://escher.github.io/1-0-0/6/maps/Escherichia%20coli/e_coli_core.Core%20metabolism.json

Exception: display_in_notebook is deprecated. The Builder is now a Jupyter Widget, so you can return the Builder in a cell to see it, or use the IPython display function (see Escher docs for details)

### Further constraints to the FVA

FVA examines how extreme the fluxes for each reaction can be. This includes solutions with very low growth rate, or with very high total flux, that means solutions that are quite unlikely for an actual organism. We can add additional constraints to the FVA to make it a bit more realistic using the parameters `fraction_of_optimium` which sets growth rate to not go below a given ratio of the max (e.g. 0.9 which implies growth rate should not be less than 90% of the previous optimum), or `pfba_factor` which says we are not interested in solutions that have very high total absolute flux (e.g. 1.1 which implies no more than 10% over the minimum total flux).

In [18]:
flux_variability_analysis(core_model, fraction_of_optimum=0.9, loopless=True)

        maximum  minimum
ACALD    0.0000  -2.5424
ACALDt   0.0000  -2.5424
ACKr     0.0000  -3.8136
ACONTa   8.7538   3.3709
ACONTb   8.7538   3.3709
...         ...      ...
TALA     3.1389   0.0000
THD2     0.8068   0.8068
TKT1     3.1389   0.0000
TKT2     2.8549  -0.3118
TPI      9.0769   5.9381

[95 rows x 2 columns]

In [26]:
from cobra.flux_analysis import find_blocked_reactions 
flux_variability_analysis(core_model, fraction_of_optimum=0.7, pfba_factor=1.1, loopless=True)
blocked = find_blocked_reactions(core_model)
print(f'number of blocked reactions: {len(blocked)}')

number of blocked reactions: 8

### Exercises

Modify the code to explore flux ranges for $\mu \gt 0.7 \ h^{-1}$

Using FVA, determine all blocked reactions ($ v = 0 $) in the model.

## Production envelopes (5)

Production envelopes are useful to illustrate how max and min fluxes for a given reaction varies when you fix flux of another reaction to a given value. E.g, "how much can product can I get given different growth rates?"

In [18]:
from cobra.flux_analysis import production_envelope

In [27]:
prod_env = production_envelope(model, reactions=model.reactions.BIOMASS_Ec_iJO1366_core_53p95M, 
                               objective=model.reactions.EX_ac_e)

In [28]:
prod_env

,carbon_source,flux_minimum,carbon_yield_minimum,mass_yield_minimum,flux_maximum,carbon_yield_maximum,mass_yield_maximum,BIOMASS_Ec_iJO1366_core_53p95M
0,EX_glc__D_e,0.0,0.0,0.0,29.093467,0.969782,0.953505,0.000000
1,EX_glc__D_e,0.0,0.0,0.0,27.702277,0.923409,0.907910,0.051704
2,EX_glc__D_e,0.0,0.0,0.0,26.311087,0.877036,0.862316,0.103408
3,EX_glc__D_e,0.0,0.0,0.0,24.919897,0.830663,0.816721,0.155111
4,EX_glc__D_e,0.0,0.0,0.0,23.528707,0.784290,0.771126,0.206815
5,EX_glc__D_e,0.0,0.0,0.0,22.137517,0.737917,0.725532,0.258519
6,EX_glc__D_e,0.0,0.0,0.0,20.746327,0.691544,0.679937,0.310223
7,EX_glc__D_e,0.0,0.0,0.0,19.352198,0.645073,0.634246,0.361926
8,EX_glc__D_e,0.0,0.0,0.0,17.955282,0.598509,0.588464,0.413630
9,EX_glc__D_e,0.0,0.0,0.0,16.553583,0.551786,0.542525,0.465334
10,EX_glc__D_e,0.0,0.0,0.0,15.091355,0.503045,0.494602,0.517038
11,EX_glc__D_e,0.0,0.0,0.0,13.629127,0.454304,0.446679,0.568742
12,EX_glc__D_e,0.0,0.0,0.0,12.166899,0.405563,0.398756,0.620445
13,EX_glc__D_e,0.0,0.0,0.0,10.690470,0.356349,0.350368,0.672149
14,EX_glc__D_e,0.0,0.0,0.0,9.191568,0.306386,0.301243,0.723853
15,EX_glc__D_e,0.0,0.0,0.0,7.493955,0.249798,0.245606,0.775557
16,EX_glc__D_e,0.0,0.0,0.0,5.753441,0.191781,0.188562,0.827260
17,EX_glc__D_e,0.0,0.0,0.0,3.835628,0.127854,0.125708,0.878964
18,EX_glc__D_e,0.0,0.0,0.0,1.917814,0.063927,0.062854,0.930668
19,EX_glc__D_e,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.982372

In [30]:
%matplotlib inline

In [31]:
prod_env[prod_env.direction == 'maximum'].plot(kind='line', x='BIOMASS_Ec_iJO1366_core_53p95M', y='carbon_yield')

AttributeError: 'DataFrame' object has no attribute 'direction'

## Gene and reaction essentiality (5 + 5)

Which genes and reactions can knock-out and which are essential?

In [32]:
from cobra.flux_analysis import single_gene_deletion, single_reaction_deletion

In [ ]:
gene_deletions = single_gene_deletion(model)
print(f'Genes: {gene_deletions}')
reaction_deletions = single_reaction_deletion(model)
print(f'Reactions: {reaction_deletions}')

Genes:           ids    growth   status
0     {b3540}  0.982372  optimal
1     {b4152}  0.982372  optimal
2     {b0394}  0.982372  optimal
3     {b2378}  0.982372  optimal
4     {b0485}  0.982372  optimal
...       ...       ...      ...
1362  {b4227}  0.982372  optimal
1363  {b4130}  0.982372  optimal
1364  {b1714}  0.982372  optimal
1365  {b0033}  0.982372  optimal
1366  {b0243}  0.981472  optimal

[1367 rows x 3 columns]
reactions:                 ids    growth   status
0            {GAPD}  0.856060  optimal
1        {3HCINNMH}  0.982372  optimal
2     {EX_malthx_e}  0.982372  optimal
3       {ASCBptspp}  0.982372  optimal
4       {CDAPPA141}  0.982372  optimal
...             ...       ...      ...
2578     {EX_gmp_e}  0.982372  optimal
2579       {CO2tpp}  0.918972  optimal
2580    {MLDCP1Bpp}  0.982372  optimal
2581      {AGMt2pp}  0.982372  optimal
2582       {GHBDHx}  0.982372  optimal

[2583 rows x 3 columns]

A gene/reaction can be considered essential if removing it leads to an infeasible model, or a model with very low growth rate.

In [ ]:
set(gene_deletions[(gene_deletions.flux < 0.01) | (gene_deletions.status != 'optimal')].index)
set(reaction_deletion[(reaction_deletions.flux < 0.01) | (reaction_deletions.statue != 'optimal')].index)

AttributeError: 'DataFrame' object has no attribute 'flux'

Or use the convenience function

In [39]:
from cobra.flux_analysis import find_essential_genes, find_essential_reactions
find_essential_genes(model)
print('reactions')
find_essential_reactions(model)

reactions

{<Reaction 3OAR140 at 0x201084d6c30>,
 <Reaction 3OAS140 at 0x201084fce30>,
 <Reaction 5DOAN at 0x20108525730>,
 <Reaction A5PISO at 0x20108525d90>,
 <Reaction ACCOAC at 0x20108572240>,
 <Reaction ACGK at 0x20108573350>,
 <Reaction ACGS at 0x20108573c80>,
 <Reaction ACHBS at 0x20108573e30>,
 <Reaction ACLS at 0x201085b8320>,
 <Reaction ACODA at 0x201085ba750>,
 <Reaction ACONTa at 0x201085bae70>,
 <Reaction ACONTb at 0x201085baa20>,
 <Reaction ACOTA at 0x201085bb380>,
 <Reaction ADCL at 0x201086051f0>,
 <Reaction ADCS at 0x20108605400>,
 <Reaction ADSK at 0x201086078f0>,
 <Reaction ADSL1r at 0x201086073b0>,
 <Reaction ADSL2r at 0x201086079e0>,
 <Reaction ADSS at 0x20108607c80>,
 <Reaction AGPAT160 at 0x20108649e80>,
 <Reaction AGPAT161 at 0x20108649fd0>,
 <Reaction AGPR at 0x2010864a3c0>,
 <Reaction AHCYSNS at 0x2010864a4b0>,
 <Reaction AICART at 0x2010864aa80>,
 <Reaction AIRC2 at 0x2010864ac00>,
 <Reaction AIRC3 at 0x2010864ad50>,
 <Reaction ALAALAr at 0x2010864b3e0>,
 <Reaction ALAR at 0x201086902f0>,
 <Reaction AMAOTr at 0x201086dcb30>,
 <Reaction AMPMS2 at 0x201086dce60>,
 <Reaction ANPRT at 0x201086ddfd0>,
 <Reaction ANS at 0x201086de210>,
 <Reaction AOXSr2 at 0x201086ddb80>,
 <Reaction APRAUR at 0x2010871c650>,
 <Reaction ARGSL at 0x2010871eab0>,
 <Reaction ARGSS at 0x2010871ebd0>,
 <Reaction ASAD at 0x2010871f770>,
 <Reaction ASP1DC at 0x20108774c50>,
 <Reaction ASPCT at 0x20108775880>,
 <Reaction ASPK at 0x20108775a00>,
 <Reaction ASPTA at 0x20108776690>,
 <Reaction ATPPRT at 0x20108777bf0>,
 <Reaction BIOMASS_Ec_iJO1366_core_53p95M at 0x201083079e0>,
 <Reaction BMOCOS at 0x201087c0b00>,
 <Reaction BMOGDS1 at 0x201087c0ce0>,
 <Reaction BMOGDS2 at 0x201087c0e90>,
 <Reaction BPNT at 0x201087c13a0>,
 <Reaction BTS5 at 0x201087c1c70>,
 <Reaction CA2tex at 0x201087c2c00>,
 <Reaction CAt6pp at 0x201087c3380>,
 <Reaction CDPMEK at 0x201088066c0>,
 <Reaction CHORM at 0x20108807f80>,
 <Reaction CHORS at 0x20108807e00>,
 <Reaction CHRPL at 0x20108807bf0>,
 <Reaction CLt3_2pp at 0x20108852930>,
 <Reaction CLtex at 0x20108852ab0>,
 <Reaction COBALT2tex at 0x20108853e00>,
 <Reaction COBALT2tpp at 0x20108853f80>,
 <Reaction CPMPS at 0x20108891a60>,
 <Reaction CS at 0x20108893a10>,
 <Reaction CTPS2 at 0x201088e4bc0>,
 <Reaction CU2tex at 0x201088e4c80>,
 <Reaction CU2tpp at 0x201088e53d0>,
 <Reaction CYSS at 0x201088e6e70>,
 <Reaction CYSTL at 0x201088e7500>,
 <Reaction DAPDC at 0x2010892b980>,
 <Reaction DAPE at 0x2010892bb00>,
 <Reaction DASYN160 at 0x20108974590>,
 <Reaction DASYN161 at 0x201089746e0>,
 <Reaction DB4PS at 0x20108974ce0>,
 <Reaction DBTS at 0x20108974ef0>,
 <Reaction DDPA at 0x201089765d0>,
 <Reaction DHAD1 at 0x20108977410>,
 <Reaction DHAD2 at 0x20108977350>,
 <Reaction DHDPRy at 0x201089b42c0>,
 <Reaction DHDPS at 0x201089b47d0>,
 <Reaction DHFR at 0x201089b49e0>,
 <Reaction DHFS at 0x201089b4bc0>,
 <Reaction DHNPA2r at 0x201089b53a0>,
 <Reaction DHORTS at 0x201089b5bb0>,
 <Reaction DHPPDA2 at 0x201089b5d60>,
 <Reaction DHPS2 at 0x201089b6240>,
 <Reaction DHPTDCs2 at 0x201089b6450>,
 <Reaction DHQS at 0x201089b6a20>,
 <Reaction DHQTi at 0x201089b6960>,
 <Reaction DMATT at 0x201089b7800>,
 <Reaction DM_4crsol_c at 0x20108304080>,
 <Reaction DM_5drib_c at 0x20108307140>,
 <Reaction DM_amob_c at 0x20108307620>,
 <Reaction DM_mththf_c at 0x20108307500>,
 <Reaction DNMPPA at 0x201089f8bc0>,
 <Reaction DNTPPA at 0x201089f9010>,
 <Reaction DPCOAK at 0x201089f99a0>,
 <Reaction DPR at 0x201089f9b50>,
 <Reaction DTMPK at 0x201089fb200>,
 <Reaction DXPRIi at 0x20108a402f0>,
 <Reaction DXPS at 0x20108a40680>,
 <Reaction E4PD at 0x20108a409e0>,
 <Reaction EGMEACPR at 0x20108a85eb0>,
 <Reaction EPMEACPR at 0x20108a86ae0>,
 <Reaction EX_ca2_e at 0x20108369790>,
 <Reaction EX_cl_e at 0x2010836a150>,
 <Reaction EX_cobalt2_e at 0x2010836a2a0>,
 <Reaction EX_cu2_e at 0x2010836adb0>,
 <Reaction EX_glc__D_e at 0x201083a6900>,
 <Reaction EX_k_e at 0x201083d5520>,
 <Reaction EX_meoh_e at 0x201083d64e0>,
 <Reaction EX_mg2_e at 0x201083d6de0>,
 <Reaction EX_mn2_e at 0x201083d7140>,
 <Reaction EX_mobd_e at 0x201083d6ed0>,
 <Reaction EX_nh4_e at 0x201083d75c0>,
 <Reaction EX_ni2_e at 0x201083d76b0>,
 <Reaction EX_pi_e at 0x20108408a40>,
 <Reaction EX_so4_e at 0x2010840a0f0>,
 <Reaction EX_zn2_e at 0x201084346e0>,
 <Reaction FCLT at 0x20108b20950>,
 <Reaction FMNAT at 0x20108bbc860>,
 <Reaction G1PACT at 0x20108c047d0>,
 <Reaction G1SAT at 0x20108c05160>,
 <Reaction G3PD2 at 0x20108c06750>,
 <Reaction G5SADs at 0x20108c408c0>,
 <Reaction GCALDD at 0x20108c88b60>,
 <Reaction GF6PTA at 0x20108c8a030>,
 <Reaction GK1 at 0x20108c8aff0>,
 <Reaction GLNS at 0x20108cca2a0>,
 <Reaction GLUPRT at 0x20108ccbce0>,
 <Reaction GLUR at 0x20108ccbe60>,
 <Reaction GLUTRR at 0x20108d0c050>,
 <Reaction GLUTRS at 0x20108d0c200>,
 <Reaction GMPS2 at 0x20108d62060>,
 <Reaction GRTT at 0x20108d63ef0>,
 <Reaction GTPCI at 0x20108da5d60>,
 <Reaction GTPCII2 at 0x20108da58e0>,
 <Reaction HBZOPT at 0x20108ded0a0>,
 <Reaction HCO3E at 0x20108dedf70>,
 <Reaction HISTD at 0x20108def890>,
 <Reaction HISTP at 0x20108e28530>,
 <Reaction HMBS at 0x20108e293d0>,
 <Reaction HPPK2 at 0x20108e29d90>,
 <Reaction HSDy at 0x20108e2aa50>,
 <Reaction HSK at 0x20108e2ac90>,
 <Reaction HSST at 0x20108e2aea0>,
 <Reaction HSTPT at 0x20108e2b050>,
 <Reaction ICDHyr at 0x20108e798b0>,
 <Reaction ICYSDS at 0x20108e7a4e0>,
 <Reaction IG3PS at 0x20108e7aed0>,
 <Reaction IGPDH at 0x20108e7b140>,
 <Reaction IGPS at 0x20108e7b470>,
 <Reaction ILETA at 0x20108e7b2f0>,
 <Reaction IMPC at 0x20108e7bfb0>,
 <Reaction IPMD at 0x20108eb95b0>,
 <Reaction IPPMIa at 0x20108eb9a30>,
 <Reaction IPPMIb at 0x20108eb9c10>,
 <Reaction IPPS at 0x20108eba060>,
 <Reaction K2L4Aabcpp at 0x20108eba8d0>,
 <Reaction K2L4Aabctex at 0x20108eba9c0>,
 <Reaction KARA1 at 0x20108ebac30>,
 <Reaction KARA2 at 0x20108ebafc0>,
 <Reaction KDOCT2 at 0x20108ebacf0>,
 <Reaction KDOPP at 0x20108ebb7a0>,
 <Reaction KDOPS at 0x20108ebb950>,
 <Reaction Ktex at 0x20108f007a0>,
 <Reaction LEUTAi at 0x20108f02e70>,
 <Reaction LPADSS at 0x20108f40fb0>,
 <Reaction MALCOAMT at 0x20108fe8800>,
 <Reaction MCOATA at 0x20108333a70>,
 <Reaction MCTP1App at 0x20108368e90>,
 <Reaction MECDPDH5 at 0x201083d6ff0>,
 <Reaction MECDPS at 0x201083d7c80>,
 <Reaction MEOHtex at 0x2010840a180>,
 <Reaction MEOHtrpp at 0x2010840aa20>,
 <Reaction MEPCT at 0x2010840b0e0>,
 <Reaction METAT at 0x2010840b5f0>,
 <Reaction METS at 0x20108436630>,
 <Reaction MG2tex at 0x2010846fe90>,
 <Reaction MNtex at 0x20108fe9850>,
 <Reaction MOADSUx at 0x20108fea210>,
 <Reaction MOAT2 at 0x20108feaab0>,
 <Reaction MOAT at 0x20108fea5d0>,
 <Reaction MOBDabcpp at 0x20108feb320>,
 <Reaction MOBDtex at 0x20108feb770>,
 <Reaction MOCOS at 0x201090ec3b0>,
 <Reaction MOHMT at 0x201090ecd10>,
 <Reaction MPTAT at 0x201090ed5b0>,
 <Reaction MPTG at 0x201090ec4d0>,
 <Reaction MPTS at 0x201090edf70>,
 <Reaction MPTSS at 0x201090ee510>,
 <Reaction MTHFR2 at 0x2010910c560>,
 <Reaction MTHTHFSs at 0x2010910c8f0>,
 <Reaction NADK at 0x20109134ad0>,
 <Reaction NADS1 at 0x20109136150>,
 <Reaction NDPK2 at 0x20109158230>,
 <Reaction NDPK4 at 0x20109158aa0>,
 <Reaction NH4tex at 0x20109158ef0>,
 <Reaction NH4tpp at 0x201091592e0>,
 <Reaction NI2tex at 0x2010915b260>,
 <Reaction NNATr at 0x2010917d700>,
 <Reaction NNDPR at 0x2010917de50>,
 <Reaction OCBT at 0x2010921eb40>,
 <Reaction OCTDPS at 0x2010921f170>,
 <Reaction OGMEACPD at 0x2010921f6e0>,
 <Reaction OGMEACPR at 0x2010921f920>,
 <Reaction OGMEACPS at 0x2010921f950>,
 <Reaction OHPBAT at 0x2010921f890>,
 <Reaction OMCDC at 0x2010921fdd0>,
 <Reaction OMPDC at 0x201092684d0>,
 <Reaction OPHBDC at 0x20109268740>,
 <Reaction OPMEACPD at 0x20109269040>,
 <Reaction OPMEACPR at 0x201092692b0>,
 <Reaction OPMEACPS at 0x20109269310>,
 <Reaction ORPT at 0x2010926a1e0>,
 <Reaction P5CR at 0x2010926ac60>,
 <Reaction PANTS at 0x201092b44d0>,
 <Reaction PAPPT3 at 0x201092b5a30>,
 <Reaction PDX5PS at 0x201092b67b0>,
 <Reaction PE160abcpp at 0x201092b78f0>,
 <Reaction PE161abcpp at 0x201092b7ad0>,
 <Reaction PERD at 0x201092fc440>,
 <Reaction PGAMT at 0x201092fe030>,
 <Reaction PHETA1 at 0x20109359850>,
 <Reaction PItex at 0x2010935b260>,
 <Reaction PMDPHT at 0x201093a75c0>,
 <Reaction PMEACPE at 0x201093a7740>,
 <Reaction PMPK at 0x201093a7920>,
 <Reaction PNTK at 0x201093a7a70>,
 <Reaction PPBNGS at 0x201093fcfb0>,
 <Reaction PPCDC at 0x201093fda60>,
 <Reaction PPNCL2 at 0x201093fdfa0>,
 <Reaction PPND at 0x201093fe420>,
 <Reaction PPNDH at 0x201093fec30>,
 <Reaction PRAGSr at 0x201093ffc20>,
 <Reaction PRAIS at 0x201094440b0>,
 <Reaction PRAIi at 0x201093ffb60>,
 <Reaction PRAMPC at 0x201094443b0>,
 <Reaction PRASCSi at 0x20109444410>,
 <Reaction PRATPP at 0x20109444260>,
 <Reaction PRFGS at 0x20109444a40>,
 <Reaction PRMICI at 0x20109444980>,
 <Reaction PSCVT at 0x201094460c0>,
 <Reaction PSD160 at 0x20109446990>,
 <Reaction PSD161 at 0x20109446b40>,
 <Reaction PSSA160 at 0x20109447ce0>,
 <Reaction PSSA161 at 0x20109447ec0>,
 <Reaction PTPATi at 0x201094945c0>,
 <Reaction QULNS at 0x201094d8710>,
 <Reaction RBFK at 0x201094d9850>,
 <Reaction RBFSa at 0x201094d9af0>,
 <Reaction RBFSb at 0x201094d9cd0>,
 <Reaction RHCCE at 0x201094da960>,
 <Reaction SADT2 at 0x20109558d10>,
 <Reaction SDPDS at 0x20109559e50>,
 <Reaction SDPTA at 0x2010955a090>,
 <Reaction SERAT at 0x2010955b5f0>,
 <Reaction SHCHD2 at 0x20109598ad0>,
 <Reaction SHCHF at 0x20109598e00>,
 <Reaction SHK3Dr at 0x20109598d40>,
 <Reaction SHKK at 0x201095992e0>,
 <Reaction SHSL1 at 0x201095995b0>,
 <Reaction SO4tex at 0x2010959a8a0>,
 <Reaction SULRi at 0x201095e2420>,
 <Reaction TDSK at 0x20109624ce0>,
 <Reaction THDPS at 0x20109625640>,
 <Reaction THRD_L at 0x20109626630>,
 <Reaction THRS at 0x20109627230>,
 <Reaction THZPSN3 at 0x20109627e00>,
 <Reaction TMDS at 0x20109666390>,
 <Reaction TMPK at 0x201096666c0>,
 <Reaction TMPPP at 0x201096668d0>,
 <Reaction TYRL at 0x201096ae210>,
 <Reaction TYRTA at 0x201096aea50>,
 <Reaction U23GAAT at 0x201096af560>,
 <Reaction UAAGDS at 0x201096aede0>,
 <Reaction UAGAAT at 0x201096f0320>,
 <Reaction UAGCVT at 0x201096f0230>,
 <Reaction UAGDP at 0x201096f0620>,
 <Reaction UAGPT3 at 0x201096f0530>,
 <Reaction UAMAGS at 0x201096f0770>,
 <Reaction UAMAS at 0x201096f0b60>,
 <Reaction UAPGR at 0x201096f0e60>,
 <Reaction UDCPDP at 0x201096f0da0>,
 <Reaction UDCPDPS at 0x201096f0fe0>,
 <Reaction UGMDDS at 0x201096f2e70>,
 <Reaction UHGADA at 0x201096f2fc0>,
 <Reaction UMPK at 0x201096f3890>,
 <Reaction UPP3MT at 0x20109734470>,
 <Reaction UPP3S at 0x20109734710>,
 <Reaction UPPDC1 at 0x20109734170>,
 <Reaction USHD at 0x201097363f0>,
 <Reaction Zn2tex at 0x20109785af0>}

### Exercise

1. Find the essential reactions instead of genes.
2. MOMA is a common approach simulation approach to use instead of FBA when doing knock-out simulations. Briefly, MOMA adds constraints to minimize the deviation from the state without the knock-out, causing smaller effects. Use `method='linear moma'` to simulate MOMA gene deletions.